import type { AppEnergyData } from "./schema";

export const STORAGE_KEY = "alitapwatt_data";

export const EMPTY_ENERGY: AppEnergyData = {
  estimatedBill: 0,
  lastMonthBill: 0,
  currentUsage: 0,
  budgetTotal: 3000,
  budgetLeft: 3000,
  savings: 0,
  savingsPct: 0,
  energyScore: 0,
  scoreEfficiency: 0,
  scoreBudget: 100,
  scorePeak: 100,
  dailyAverage: 0,
  daysElapsed: 0,
  lastMonthKwh: 0,
  dailyData: [0, 0, 0, 0, 0, 0, 0],
  weeklyData: [0, 0, 0, 0, 0, 0, 0],
  prevWeek: [0, 0, 0, 0, 0, 0, 0],
  peakHours: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  predictedBill: 0,
  totalSavingsYear: 0,
  avgBill: 0,
  lowestMonth: 0,
  lowestMonthLabel: "—",
  highestMonth: 0,
  highestMonthLabel: "—",
  months: [],
  timeline: [],
  achievements: [],
  monthlyData: [],
  notifications: [],
  liveCost: 0,
  liveKw: 0,
  projectedDaily: 0,
  smartDevices: [],
  automationRules: [],
  userName: "User",
};

export const SEED_ENERGY: AppEnergyData = {
  estimatedBill: 2485,
  lastMonthBill: 2820,
  currentUsage: 186,
  budgetTotal: 3000,
  budgetLeft: 515,
  savings: 335,
  savingsPct: 15,
  energyScore: 72,
  scoreEfficiency: 78,
  scoreBudget: 82,
  scorePeak: 55,
  dailyAverage: 6.2,
  daysElapsed: 24,
  lastMonthKwh: 248,
  dailyData: [28, 35, 22, 40, 32, 48, 55],
  weeklyData: [42, 55, 48, 62, 58, 75, 70],
  prevWeek: [50, 60, 55, 68, 65, 80, 78],
  peakHours: [18, 22, 35, 48, 62, 75, 68, 55, 40, 30, 20, 12],
  predictedBill: 3180,
  totalSavingsYear: 5240,
  avgBill: 2740,
  lowestMonth: 2350,
  lowestMonthLabel: "November",
  highestMonth: 3100,
  highestMonthLabel: "July",
  months: [
    { name: "January 2026", bill: 2540, kwh: 198, change: -12, insight: "You reduced nighttime appliance usage, resulting in lower costs." },
    { name: "December 2025", bill: 2890, kwh: 215, change: 8, insight: "Holiday celebrations increased overall consumption." },
    { name: "November 2025", bill: 2680, kwh: 204, change: -5, insight: "AC usage dropped as weather cooled down." },
    { name: "October 2025", bill: 2820, kwh: 210, change: 3, insight: "Slight increase due to hotter-than-usual days." },
    { name: "September 2025", bill: 2740, kwh: 208, change: -8, insight: "AI recommendations helped reduce peak hour usage." },
    { name: "August 2025", bill: 2980, kwh: 225, change: 15, insight: "Extended AC usage during summer heatwave." },
  ],
  timeline: [
    { text: "High AC usage detected during summer months.", date: "Aug 2025", type: "warn" },
    { text: "AI recommendations applied — peak usage reduced by 12%.", date: "Sep 2025", type: "good" },
    { text: "New washing machine added — slight increase in April.", date: "Apr 2025", type: "info" },
    { text: "Home became 18% more efficient this quarter.", date: "Mar 2025", type: "good" },
    { text: "Budget exceeded by 6% in February.", date: "Feb 2025", type: "warn" },
    { text: "First ₱5,000 savings milestone reached!", date: "Jan 2025", type: "good" },
  ],
  achievements: [
    { label: "₱5,000 Saved", desc: "Total savings milestone achieved" },
    { label: "3-Month Streak", desc: "Consistently under budget" },
    { label: "Eco Household", desc: "Reduced carbon footprint by 15%" },
    { label: "Tipid Master", desc: "Top 10% of savers in Laguna" },
  ],
  monthlyData: [2540, 2890, 2680, 2820, 2740, 2980, 3100, 2850, 2600, 2450, 2350, 2540],
  notifications: [
    { type: "warn", title: "Near budget limit", desc: "You've used 85% of your ₱3,000 monthly budget.", time: "2h ago" },
    { type: "info", title: "Usage spike detected", desc: "Today's consumption is 23% higher than usual.", time: "5h ago" },
    { type: "good", title: "Savings milestone", desc: "You saved ₱335 this month — 15% less than last month!", time: "1d ago" },
    { type: "info", title: "New AI tip available", desc: "Try setting AC to 24°C to save ₱300/month.", time: "2d ago" },
  ],
  liveCost: 4.32,
  liveKw: 1.8,
  projectedDaily: 104,
  smartDevices: [
    { name: "Air Conditioner", watts: 1250, cost: "₱12/hr", daily: "8.2 kWh", status: "ON", rating: "High", health: 85, suggestion: "Reduce to 24°C to save energy." },
    { name: "Refrigerator", watts: 180, cost: "₱1.7/hr", daily: "2.8 kWh", status: "ON", rating: "Good", health: 72, suggestion: "Check door seal for efficiency." },
    { name: "Smart Plug", watts: 0, cost: "₱0/hr", daily: "0 kWh", status: "OFF", rating: "—", health: 98, suggestion: "Plug idle devices to automate." },
    { name: "Television", watts: 120, cost: "₱1.1/hr", daily: "1.4 kWh", status: "ON", rating: "Good", health: 90, suggestion: "Turn off when not in use." },
    { name: "Rice Cooker", watts: 700, cost: "₱6.7/hr", daily: "0.7 kWh", status: "OFF", rating: "—", health: 95, suggestion: "Unplug after cooking." },
    { name: "Washing Machine", watts: 500, cost: "₱4.8/hr", daily: "0.5 kWh", status: "OFF", rating: "—", health: 88, suggestion: "Use cold wash cycle." },
    { name: "Electric Fan", watts: 75, cost: "₱0.7/hr", daily: "5.2 kWh", status: "ON", rating: "Excellent", health: 92, suggestion: "Optimal usage — keep it up!" },
    { name: "Lights", watts: 60, cost: "₱0.6/hr", daily: "1.1 kWh", status: "ON", rating: "Good", health: 100, suggestion: "Switch to LED to save more." },
    { name: "Gaming PC", watts: 450, cost: "₱4.3/hr", daily: "3.6 kWh", status: "OFF", rating: "—", health: 80, suggestion: "Enable power saving mode." },
    { name: "Water Heater", watts: 3000, cost: "₱28.8/hr", daily: "1.5 kWh", status: "OFF", rating: "—", health: 65, suggestion: "Use timer to limit runtime." },
  ],
  automationRules: [
    { label: "Turn off lights at 12AM", active: true },
    { label: "Alert if AC runs > 8 hours", active: true },
    { label: "Notify on refrigerator spike", active: false },
  ],
  userName: "Kent",
};
